format = """
[](#9A348E)\
$battery\
$username\
[](bg:#DA627D fg:#9A348E)\
$directory\
[](fg:#DA627D bg:#FCA17D)\
$git_branch\
$git_status\
[](fg:#FCA17D bg:#33658A)\
$time\
[ ](fg:#33658A)\
"""

add_newline = false

[battery]
disabled = false
format='[$symbol$percentage]($style)'

[[battery.display]]
threshold = 90
style = 'bg:#9A348E fg:#DA627D'
charging_symbol = '⚡️'
discharging_symbol = '💀'

[directory]
style = "bg:#DA627D"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[git_branch]
symbol = ""
style = "bg:#FCA17D"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:#FCA17D"
format = '[$all_status$ahead_behind ]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#33658A"
format = '[ 󰧼 $time ]($style)'